Projeto.CRUD/Models/Model/ProdutoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Projeto.CRUD.Models.Model
{
    public class ProdutoModel
    {
        public int ProdutoId { get; set; }

        [Required(ErrorMessage="Nome é um campo obrigatório")]
        public string Nome { get; set; }

        [Required(ErrorMessage="Preço é um campo obrigatório")]
        public double Preco { get; set; }

        [Required(ErrorMessage="Data de Cadastro é um campo obrigatório")]
        [DataType(DataType.Date)]
        public DateTime DataCadastro { get; set; }

        [Required(ErrorMessage="Quantidade é um campo obrigatório")]
        public int Quantidade { get; set; }
    }
}

Projeto.CRUD/Models/Negocio/ProdutoNegocio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Projeto.CRUD.Models.Model;
using Projeto.CRUD.Models.Repositorio;

namespace Projeto.CRUD.Models.Negocio
{
    /// <summary>
    /// Essa classe só serve para poder transitar os dados de uma camada para outra
    /// </summary>
    public class ProdutoNegocio
    {
        public void Cadastrar(ProdutoModel produto)
        {
            new ProdutoRepositorio().Cadastrar(produto);
        }

        public void Atualizar(ProdutoModel produto)
        {
            new ProdutoRepositorio().Atualizar(produto);
        }

        public void Deletar(int idProduto)
        {
            new ProdutoRepositorio().Deletar(idProduto);
        }

        public ProdutoModel GetById(int id)
        {
            return new ProdutoRepositorio().GetById(id);
        }

        public IEnumerable<ProdutoModel> Listar()
        {
            return new ProdutoRepositorio().Listar();
        }
    }
}

Projeto.CRUD/Models/Repositorio/ProdutoRepositorio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Projeto.CRUD.Models.Model;

namespace Projeto.CRUD.Models.Repositorio
{
    public class ProdutoRepositorio
    {
        /// <summary>
        /// Criamos uma lista estática, uma vez que o foco não é o banco:
        /// </summary>
        private static List<ProdutoModel> _listaProdutos;

        /// <summary>
        /// Construtor da Classe:
        /// </summary>
        public ProdutoRepositorio()
        {
            //Caso a lista não for instanciada, criará uma nova instância:
            if (_listaProdutos == null)
            {
                _listaProdutos = new List<ProdutoModel>();

                //Para iniciar já com um dado na lista:
                _listaProdutos.Add(new ProdutoModel
                {
                    ProdutoId = 1,
                    Nome = "Mouse Microsoft",
                    Preco = 18.20,
                    DataCadastro = DateTime.Now,
                    Quantidade = 1
                });
            }
        }

        /// <summary>
        /// Método para Cadastrar uma nova Pessoa:
        /// </summary>
        /// <param name="produto"></param>
        public void Cadastrar(ProdutoModel produto)
        {
            //O Id do Produto já iniciará com 1
            var y = 1;

            //Criamos um laço para que possa incrementar o Id do Produto
            //A cada cadastro novo de um determinado Produto irá incrementar
            while (_listaProdutos.Any(x => x.ProdutoId == y))
                y++;
            produto.ProdutoId = y;

            _listaProdutos.Add(produto);
        }

        /// <summary>
        /// Método para retornar o objeto que possuir o "ID" expecífico:
        /// </summary> 
        public ProdutoModel GetById(int id)
        {
            return _listaProdutos.SingleOrDefault(x => x.ProdutoId == id);
        }

        /// <summary>
        /// Método para atualizar a Pessoa. Mas, antes vai averiguar se já tem algum dato referente a determinada Pessoa:
        /// </summary>
        public void Atualizar(ProdutoModel produto)
        {
            var produtoJaCadastrado = GetById(produto.ProdutoId);
            if (produtoJaCadastrado != null)
            {
                foreach (var propertyInfo in typeof(ProdutoModel).GetProperties().Where(x=> x.Name != "ProdutoId"))
                {
                    //O primeiro parâmetro: "pessoaJaRegistrada é o objeto antigo
                    //O segundo parâmetro: "propertyInfo" vai setear o novo valor
                    propertyInfo.SetValue(produtoJaCadastrado, propertyInfo.GetValue(produto));
                }
            }
        }

        /// <summary>
        /// Método para Deletar uma Pessoa:
        /// </summary>
        public void Deletar(int id)
        {
           //Antes de deletar uma determinada Pessoa, temos que primeiro encontrar qual "id" queremos deletar: 
            var obj = GetById(id);

            //Depois que encontrar o determinado "id" que eu quero remover aí.....
            _listaProdutos.Remove(obj);
        }

        /// <summary>
        ///Método para listar todas as Pessoas: SelectAll
        /// </summary>
        public IEnumerable<ProdutoModel> Listar()
        {
            //se for nulo retornará null, senão retornará a lista completa
            return _listaProdutos ?? _listaProdutos;
        }
    }
}

Projeto.CRUD/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Projeto.CRUD.Models.Model;
using Projeto.CRUD.Models.Negocio;

namespace Projeto.CRUD.Controllers
{
    public class AppController : Controller
    {
        // GET: App
        public ActionResult Index()
        {
            return View();
        }

        //Método: Cadastrar
        //POST: App
        [HttpPost]
        public void Cadastrar(ProdutoModel produto)
        {
            try
            {
                new ProdutoNegocio().Cadastrar(produto);
            }
            catch (Exception ex)
            {
                throw new Exception("Erro ao cadastrar o Produto " + ex.Message);
            }
        }

        //Método: Editar:
        //GET: App
        public ActionResult Editar(int id)
        {
            try
            {
                //Para realizar a edição, primeiro temos que localizar o id, para depois
                //realizar a atualização:
                var produto = new ProdutoNegocio().GetById(id);

                return Json(produto, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw new Exception("Erro ao editar o Produto " + ex.Message);
            }
        }

        //Método: Atualizar:
        //POST: App
        [HttpPost]
        public void Atualizar(ProdutoModel produto)
        {
            try
            {
                new ProdutoNegocio().Atualizar(produto);
            }
            catch (Exception ex)
            {
                throw new Exception("Erro ao atualizar o Produto " + ex.Message);
            }
        }

        //Método: Deletar:
        public void Deletar(int id)
        {
            try
            {
                new ProdutoNegocio().Deletar(id);
            }
            catch (Exception ex)
            {
                throw new Exception("Erro ao delatar o Produto " + ex.Message);
            }
        }

        //Método: Listar todos os Produtos:
        //GET: App
        [HttpGet]
        public ActionResult Listar()
        {
            try
            {
                var listaProdutos = new ProdutoNegocio().Listar();
                return Json(listaProdutos, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw new Exception("Erro ao listar o(s) Produto(s) " + ex.Message);
            }
        }
    }
}

Projeto.CRUD/Views/App/Index.cshtml
@{
    ViewBag.Title = "Tutorial - SPA com MVC 5";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts {
    <script type="text/javascript" src="~/Scripts/App/CrudApp.js"></script>
}

<!--Seção de scripts definidas pelo RenderSection através do arquivo _Layout.cshtml na pasta Shared-->
@section styles {
    <style>
        body {
            margin: 50px;
        }
    </style>
}

<!--Usando o Bootstrap!!! =) -->
<section id="conteudo" class="container">
    <div class="form-group">
        <section id="formulario">
            <!-- Formulário da nossa página para poder adicionar e atualizar uma determinada pessoa -->
            <form action="/" method="post" id="formDados">

                <!---Esse input do tipo "hidden" estamos usando somente com a finalidade de armazenar o Id-->
                <input type="hidden" id="idProduto" name="ProdutoId" />

                <!--Fiz a chamada da função "somenteLetras" para que não permita entrada de número no campo "Nome"-->
                <div class="row">
                    <div class="form-group">
                        <label for="nome">Produto</label>
                        <input type="text" id="nome" class="form-control" name="Nome" onkeypress="return somenteLetras(event)" autofocus />
                    </div>
                </div>

                <!--Usei o atributo "step" com o objetivo de validar o campo "Preço" como sendo decimal-->
                <div class="row">
                    <div class="form-group">
                        <div class="input-group">
                            <label for="preco">Preço</label>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon" id="preco">R$</span>
                            <input type="number" step="any" id="preco" class="form-control" name="Preco" />
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <div class="input-group">
                            <label for="dataCadastro">Data de Cadastro</label>
                        </div>
                        <div class="input-group">
                            <span class="input-group-addon glyphicon glyphicon-calendar"></span>
                            <input type="date" id="dataCadastro" class="form-control" name="dataCadastro" />
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <label for="quantidade">Quantidade</label>
                        <input type="number" id="quantidade" class="form-control" name="Quantidade" />
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <button id="salvar" class="btn btn-success btn-sm" onclick=" Cadastrar() "><span class="glyphicon glyphicon-plus"></span>&nbspCadastrar</button>
                        <button id="atualizar" class="btn btn-warning btn-sm hidden" onclick=" Atualizar() "><span class="glyphicon glyphicon-pencil">&nbspAtualizar</span></button>
                    </div>
                </div>
            </form>
        </section>
    </div>

    <!--Criação da tabela-->
    <section id="listagemDeProdutos">
            <table class="table table-striped" id="tabela">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nome do Produto</th>
                        <th>Preço</th>
                        <th>Data de Cadastro</th>
                        <th>Quantidade</th>
                        <th></th>
                    </tr>
                </thead>
                <!--Esse id contendo o "tbody" é o que realizará o preenchimento da nossa tabela através do JQuery-->
                <tbody id="tbody"></tbody>
            </table>
    </section>
</section>


Projeto.CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Projeto - SPA com MVC 5</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    @RenderSection("styles", false)
</head>
<body>
    <header>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Home", "Index", "App", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav"></ul>
                </div>
            </div>
        </div>
        <div class="jumbotron">
            <h1 class="pageTitle">Projeto SPA com MVC 5</h1>
        </div>
    </header>

    <div class="container body-content">
        <section>
            @RenderBody()
        </section>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Glaucia Lemos (.NET | Full Stack Software Developer)</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>